// <auto-generated />
namespace HomeTask.Persistence.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class v10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(v10));
        
        string IMigrationMetadata.Id
        {
            get { return "201610211040462_v1.0"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
